# CheckThirdLib.cmake
# 检查并加载所有第三方库
# 根据 ProjectConfig.cmake 中定义的 DISABLE_* 开关决定是否查找对应库

message("\n===== 开始检查第三方库 =====")

# 初始化所有支持标志
include(${SU_FILE_ROOT}/cmake/InitThirdSupport.cmake)

# 加载第三方库查找模块（deps 目录）
include(${SU_FILE_ROOT}/cmake/deps/FindFMT.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindSpdLog.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindCryptoPP.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindIConv.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindCURL.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindJsonPP.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindCairo.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindFreeType.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindPNG.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindGDAL.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindEcCodes.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindNetCDF.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindGeoTIFF.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindJPEG.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindLZ4.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindZLIB.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindLibZIP.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindBZIP2.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindMiniZIP.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindGZIP.cmake)
include(${SU_FILE_ROOT}/cmake/deps/Find7ZIP.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindLibArchive.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindOpenSSL.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindProtoZero.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindSQLite3.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindPolyClipping.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindLibSpatialite.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindWebSocketPP.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindPahoMQTT.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindEigen3.cmake)
include(${SU_FILE_ROOT}/cmake/deps/FindCGAL.cmake)

message("\n===== 库检查完成 =====")

# 打印已启用的库列表
message("\n--- 已启用的第三方库 ---")
if(SU_THIRD_SUPPORT_FMT)
    message("  [✓] FMT")
endif()
if(SU_THIRD_SUPPORT_SPDLOG)
    message("  [✓] spdlog")
endif()
if(SU_THIRD_SUPPORT_CRYPTOPP)
    message("  [✓] CryptoPP")
endif()
if(SU_THIRD_SUPPORT_ICONV)
    message("  [✓] Iconv")
endif()
if(SU_THIRD_SUPPORT_CURL)
    message("  [✓] CURL")
endif()
if(SU_THIRD_SUPPORT_JSONPP)
    message("  [✓] jsoncpp")
endif()
if(SU_THIRD_SUPPORT_CAIRO)
    message("  [✓] Cairo")
endif()
if(SU_THIRD_SUPPORT_FREE_TYPE)
    message("  [✓] FreeType")
endif()
if(SU_THIRD_SUPPORT_PNG)
    message("  [✓] PNG")
endif()
if(SU_THIRD_SUPPORT_GDAL)
    message("  [✓] GDAL")
endif()
if(SU_THIRD_SUPPORT_ECCODES)
    message("  [✓] EcCodes (GRIB2)")
endif()
if(SU_THIRD_SUPPORT_NETCDF_CXX)
    message("  [✓] netCDFCxx")
endif()
if(SU_THIRD_SUPPORT_GEOTIFF)
    message("  [✓] GeoTIFF")
endif()
if(SU_THIRD_SUPPORT_JPEG)
    message("  [✓] JPEG")
endif()
if(SU_THIRD_SUPPORT_LZ4)
    message("  [✓] LZ4")
endif()
if(SU_THIRD_SUPPORT_ZLIB)
    message("  [✓] ZLIB")
endif()
if(SU_THIRD_SUPPORT_LIBZIP)
    message("  [✓] libzip")
endif()
if(SU_THIRD_SUPPORT_BZIP2)
    message("  [✓] BZip2")
endif()
if(SU_THIRD_SUPPORT_MINI_ZIP)
    message("  [✓] MiniZIP")
endif()
if(SU_THIRD_SUPPORT_GZIP)
    message("  [✓] GZIP")
endif()
if(SU_THIRD_SUPPORT_7ZIP)
    message("  [✓] 7-Zip")
endif()
if(SU_THIRD_SUPPORT_LIBARCHIVE)
    message("  [✓] libarchive")
endif()
if(SU_THIRD_SUPPORT_OPENSSL)
    message("  [✓] OpenSSL")
endif()
if(SU_THIRD_SUPPORT_PROTO_ZERO)
    message("  [✓] ProtoZero")
endif()
if(SU_THIRD_SUPPORT_SQLITE3)
    message("  [✓] SQLite3")
endif()
if(SU_THIRD_SUPPORT_POLY_CLIPPING)
    message("  [✓] Clipper2")
endif()
if(SU_THIRD_SUPPORT_SPATIALITE)
    message("  [✓] SpatiaLite")
endif()
if(SU_THIRD_SUPPORT_WEBSOCKET_PP)
    message("  [✓] WebSocket++")
endif()
if(SU_THIRD_SUPPORT_PAHO_MQTT)
    message("  [✓] PahoMQTT")
endif()
if(SU_THIRD_SUPPORT_EIGEN3)
    message("  [✓] Eigen3")
endif()
if(SU_THIRD_SUPPORT_CGAL)
    message("  [✓] CGAL")
endif()
message("--------------------------------")
