message("\n检查库 lz4")
if(DISABLE_LZ4)
    message(STATUS "禁用lz4")
else()
    find_package(lz4 CONFIG REQUIRED)
    if(lz4_FOUND)
        message(STATUS "lz4 found: ${lz4_FOUND}")
        message(STATUS "lz4 version: ${lz4_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES lz4::lz4)
        set(SU_THIRD_SUPPORT_LZ4 1)
    else()
        message(WARNING "未发现lz4")
    endif()
endif()