message("\n检查库 polyclipping")
if(DISABLE_POLY_CLIPPING)
    message(STATUS "禁用polyclipping")
else()
    find_package(Clipper2 CONFIG)
    if(Clipper2_FOUND)
        message(STATUS "polyclipping found: ${Clipper2_FOUND}")
        message(STATUS "polyclipping version: ${pClipper2_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES Clipper2::Clipper2)
        set(SU_THIRD_SUPPORT_POLY_CLIPPING 1)
    else()
        message(WARNING "未发现polyclipping")
    endif()
endif()