message("\n检查库 minizip")

if(DISABLE_MINI_ZIP)
    message(STATUS "禁用minizip")
else()
    find_package(minizip CONFIG REQUIRED)
    if(minizip_FOUND)
        message(STATUS "minizip found: ${minizip_FOUND}")
        message(STATUS "minizip version: ${minizip_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES minizip::minizip)
        set(SU_THIRD_SUPPORT_MINI_ZIP 1)
    else()
        message(WARNING "未发现minizip")
    endif()
endif()