message("\n检查库 Iconv")
if(DISABLE_Iconv)
    message(STATUS "禁用Iconv")
else()
    find_package(Iconv)
    if(Iconv_FOUND)
        message(STATUS "Iconv found: ${Iconv_FOUND}")
        message(STATUS "Iconv version: ${Iconv_VERSION}")
        include_directories(${Iconv_INCLUDE_DIR})
        list(APPEND SU_ALL_REQUIRED_LIBRARIES ${Iconv_LIBRARIES})
        set(SU_THIRD_SUPPORT_ICONV 1)
    else()
        message(WARNING "未发现Iconv")
    endif()
endif()