message("\n检查库 GeoTIFF")
if(DISABLE_GEOTIFF)
    message(STATUS "禁用GeoTIFF")
else()
    find_package(GeoTIFF CONFIG)
    if(GeoTIFF_FOUND)
        message(STATUS "GeoTIFF found: ${GeoTIFF_FOUND}")
        message(STATUS "GeoTIFF version: ${GeoTIFF_VERSION}")
        include_directories(${GEOTIFF_INCLUDE_DIR})
        list(APPEND SU_ALL_REQUIRED_LIBRARIES ${GEOTIFF_LIBRARIES})
        set(SU_THIRD_SUPPORT_GEOTIFF 1)
    else()
        message(WARNING "未发现GeoTIFF")
    endif()
endif()

