message("\n检查库 SPATIALITE")
if(DISABLE_SPATIALITE)
    message(STATUS "禁用SPATIALITE")
else()
    find_package(SPATIALITE_LIB NAMES "spatialite")
    if(SPATIALITE_LIB_FOUND)
        list(APPEND SU_ALL_REQUIRED_LIBRARIES ${SPATIALITE_LIB})
        set(SU_THIRD_SUPPORT_SPATIALITE 1)
    else()
        message(WARNING "未发现SPATIALITE")
    endif()
endif()