message("\n检查库 JPEG")
if(DISABLE_JPEG)
    message(STATUS "禁用JPEG")
else()
    find_package(JPEG REQUIRED)
    if(JPEG_FOUND)
        message(STATUS "JPEG found: ${JPEG_FOUND}")
        message(STATUS "JPEG version: ${JPEG_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES ${JPEG_LIBRARIES})
        set(SU_THIRD_SUPPORT_JPEG 1)
    else()
        message(WARNING "未发现JPEG")
    endif()
endif()