message("\n检查库 ZLIB")

if(DISABLE_ZLIB)
    message(STATUS "禁用ZLIB")
else()
    find_package(ZLIB)
    if(ZLIB_FOUND)
        message(STATUS "ZLIB found: ${ZLIB_FOUND}")
        message(STATUS "ZLIB version: ${ZLIB_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES ZLIB::ZLIB)
        set(SU_THIRD_SUPPORT_ZLIB 1)
    else()
        message(WARNING "未发现ZLIB")
    endif()
endif()