message("\n检查库 polyclipping")
if(DISABLE_POLY_CLIPPING)
    message(STATUS "禁用polyclipping")
else()
    find_package(polyclipping CONFIG)
    if(polyclipping_FOUND)
        message(STATUS "polyclipping found: ${polyclipping_FOUND}")
        message(STATUS "polyclipping version: ${polyclipping_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES polyclipping::polyclipping)
        set(SU_THIRD_SUPPORT_POLY_CLIPPING 1)
    else()
        message(WARNING "未发现polyclipping")
    endif()
endif()