message("\n检查库 GZIP")
if(DISABLE_GZIP)
    message(STATUS "禁用GZIP")
else()
    find_path(GZIP_HPP_INCLUDE_DIRS "gzip/compress.hpp")
    if(GZIP_HPP_INCLUDE_DIRS)
        message(STATUS "GZIP found: ${GZIP_HPP_INCLUDE_DIRS}")
        include_directories(${GZIP_HPP_INCLUDE_DIRS})
        set(SU_THIRD_SUPPORT_GZIP 1)
    else()
        message(WARNING "未发现GZIP")
    endif()
endif()