message("\n检查库 CryptoPP")
if(DISABLE_CRYPTOPP)
    message(STATUS "禁用CryptoPP")
else()
    find_package(cryptopp CONFIG)
    if(cryptopp_FOUND)
        message(STATUS "CryptoPP found: ${cryptopp_FOUND}")
        message(STATUS "CryptoPP version: ${cryptopp_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES cryptopp::cryptopp)
        set(SU_THIRD_SUPPORT_CRYPTOPP 1)
    else()
        message(WARNING "未发现CryptoPP")
    endif()
endif()