message("\n检查库 PNG")
if(DISABLE_PNG)
    message(STATUS "禁用PNG")
else()
    find_package(PNG)
    if(PNG_FOUND)
        message(STATUS "PNG found: ${PNG_FOUND}")
        message(STATUS "PNG version: ${PNG_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES PNG::PNG)
        set(SU_THIRD_SUPPORT_PNG 1)
    else()
        message(WARNING "未发现PNG")
    endif()
endif()