message("\n检查库 CAIRO")
if(DISABLE_CAIRO)
    message(STATUS "禁用CAIRO")
else()
    find_path(CAIRO_INCLUDE_DIR cairo/cairo.h)
    set(CAIRO_NAMES ${JRTPLIB_NAMES} cairo)
    find_library(CAIRO_LIBRARY NAMES ${CAIRO_NAMES})
    if(CAIRO_INCLUDE_DIR)
        message(STATUS "CAIRO found: ${CAIRO_INCLUDE_DIR}")
        message(STATUS "CAIRO libs: ${CAIRO_LIBRARY}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES ${CAIRO_LIBRARY})
        if(IS_LINUX)
            find_package(Fontconfig REQUIRED) 
            list(APPEND SU_ALL_REQUIRED_LIBRARIES Fontconfig::Fontconfig)
            find_package(PNG REQUIRED)
            list(APPEND SU_ALL_REQUIRED_LIBRARIES PNG::PNG)
            find_library(PIXMAN_LIBRARY NAMES pixman-1)
            list(APPEND SU_ALL_REQUIRED_LIBRARIES ${PIXMAN_LIBRARY})
        endif()
        set(SU_THIRD_SUPPORT_CAIRO 1)
    else()
        message(WARNING "未发现CAIRO")
    endif()
endif()