message("\n检查库 7zip")

if(DISABLE_7ZIP)
    message(STATUS "禁用7zip")
else()
    find_package(7zip CONFIG)
    if(7zip_FOUND)
        message(STATUS "7zip found: ${7zip_FOUND}")
        message(STATUS "7zip version: ${7zip_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES 7zip::7zip)
        set(SU_THIRD_SUPPORT_7ZIP 1)
    else()
        message(WARNING "未发现7zip")
    endif()
endif()