message("\n检查库 spdlog")
if(DISABLE_SPDLOG)
    message(STATUS "禁用spdlog")
else()
    find_package(spdlog CONFIG REQUIRED)
    if(spdlog_FOUND)
        message(STATUS "spdlog found: ${spdlog_FOUND}")
        message(STATUS "spdlog version: ${spdlog_VERSION}")
        list(APPEND SU_ALL_REQUIRED_LIBRARIES  spdlog::spdlog
                spdlog::spdlog_header_only)
        set(SU_THIRD_SUPPORT_SPDLOG 1)
    else()
        message(WARNING "未发现spdlog")
    endif()
endif()