find_package(eccodes CONFIG REQUIRED)
message("\n检查ECCODES")
if (NOT "" STREQUAL "${eccodes_BASE_DIR}")
  message(STATUS ">>>>>>>>>>>>>>>> ECCODES <<<<<<<<<<<<<<<<")
  message(STATUS "BASE_DIR ${eccodes_BASE_DIR}.")
  message(STATUS "VERSION ${eccodes_VERSION}.")
  message(STATUS "DEFINITION_PATH ${ECCODES_DEFINITION_PATH}.")
  message(STATUS ">>>>>>>>>>>>>>>> ECCODES <<<<<<<<<<<<<<<<")
  add_compile_options(-DSU_ECCODES_ENABLED)
endif ()
