# 检查达梦数据库的一些信息

if(NOT DISABLE_DM8)
    if(DEFINED ENV{DM_HOME})
        SET(DM8_DPI_ROOT  $ENV{DM_HOME}/drivers/dpi)
        if(EXISTS "${DM8_DPI_ROOT}")
            SET(DM8_DPI_INCLUDE ${DM8_DPI_ROOT}/include)
            SET(DM8_DPI_LIBRARY "${DM8_DPI_ROOT}/dmdpi.${STATIC_LIB_SUFFIX}")
            message(STATUS ">>>>>>>>>>>>>>>> DM8 <<<<<<<<<<<<<<<<")
            message(STATUS "DM8 DPI ROOT ${DM8_DPI_ROOT}.")
            message(STATUS "DM8 DPI INCLUDE ${DM8_DPI_INCLUDE}.")
            message(STATUS "DM8 DPI LIBRARY ${DM8_DPI_LIBRARY}.")
            message(STATUS ">>>>>>>>>>>>>>>> DM8 <<<<<<<<<<<<<<<<\n")
            include_directories(${DM8_DPI_INCLUDE})
            link_libraries(${DM8_DPI_LIBRARY})
            file(GLOB DM8_DYNAMIC_LIBRARIES "${DM8_DPI_ROOT}/*.${DYNAMIC_LIB_SUFFIX}" )
            if(NOT EXISTS ${EXECUTABLE_OUTPUT_PATH})
                file(make_directory ${EXECUTABLE_OUTPUT_PATH})
            endif()
            foreach(dlf ${DM8_DYNAMIC_LIBRARIES})
                # file(COPY ${dlf} DESTINATION ${EXECUTABLE_OUTPUT_PATH})
                execute_process(COMMAND ${CMAKE_COMMAND} -E  copy "${dlf}" "${EXECUTABLE_OUTPUT_PATH}")
            endforeach()
            add_definitions("-DSU_DM8_DPI_ENABLED")
        endif()
    else()
        message(STATUS "FOUND DM_HOME ENV.")
    endif()
endif()

