# 检查Windows平台下GRIP_API的一些信息, Linux平台下使用 ecCodes
IF (IS_WINDOWS)
    IF ("" STREQUAL "$ENV{SU_GRIB_API_ROOT}")
        MESSAGE(WARNING "SU_GRIB_API_ROOT NOT FOUND.")
        add_definitions("-DSU_GRIB_ENABLED=0")
    ELSE ()
        SET(SU_GRIB_API_INCLUDE "$ENV{SU_GRIB_API_ROOT}/include")
        IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
            SET(GRIB_BUILD_TYPE "Debug")
        ELSE()
            SET(GRIB_BUILD_TYPE "Release")
        ENDIF()
        SET(SU_GRIB_API_LIBRARY "$ENV{SU_GRIB_API_ROOT}/lib/${GRIB_BUILD_TYPE}/grib_api_lib.lib")
        MESSAGE("USE SU_GRIB_API_INCLUDE ${SU_GRIB_API_INCLUDE}.")
        MESSAGE("USE SU_GRIB_API_LIBRARY ${SU_GRIB_API_LIBRARY}.")
        INCLUDE_DIRECTORIES(${SU_GRIB_API_INCLUDE})
        LINK_LIBRARIES(${SU_GRIB_API_LIBRARY})
        add_definitions("-DSU_GRIB_ENABLED=1")
    ENDIF ()
ELSE()
    # SET(SU_GRIB_ASSIGN TRUE)
    IF(SU_GRIB_ASSIGN)
        MESSAGE(INFO "临时处理.")
        SET(ECCODES_DIR /usr/local/eccodes)
        SET(SU_GRIB_API_INCLUDE "${ECCODES_DIR}/include")
        SET(SU_GRIB_API_LIBRARY "${ECCODES_DIR}/lib64/libeccodes.so")
        INCLUDE_DIRECTORIES(${SU_GRIB_API_INCLUDE})
        LINK_LIBRARIES(${SU_GRIB_API_LIBRARY})
        add_definitions("-DSU_GRIB_ENABLED=1")
        MESSAGE("USE SU_GRIB_API_INCLUDE ${SU_GRIB_API_INCLUDE}.")
        MESSAGE("USE SU_GRIB_API_LIBRARY ${SU_GRIB_API_LIBRARY}.")
    ELSE()
        IF("" STREQUAL "$ENV{ECCODES_DIR}")
            MESSAGE(WARNING "ECCODES_DIR NOT FOUND.")
            add_definitions("-DSU_GRIB_ENABLED=0")
        ELSE()
            SET(SU_GRIB_API_INCLUDE "$ENV{ECCODES_DIR}/include")
            SET(SU_GRIB_API_LIBRARY "$ENV{ECCODES_DIR}/lib64/libeccodes.so")
            INCLUDE_DIRECTORIES(${SU_GRIB_API_INCLUDE})
            LINK_LIBRARIES(${SU_GRIB_API_LIBRARY})
            add_definitions("-DSU_GRIB_ENABLED=1")
        ENDIF()
    ENDIF()
   
ENDIF ()