# 检查Windows平台下GRIP_API的一些信息, Linux平台下使用 ecCodes
if(NOT DISABLE_GRIB_API)
  if(IS_WINDOWS)
    if("" STREQUAL "$ENV{SU_GRIB_API_ROOT}")
      message(WARNING "SU_GRIB_API_ROOT NOT FOUND.")
      add_definitions("-DSU_GRIB_ENABLED=0")
    else()
      set(SU_GRIB_API_INCLUDE "$ENV{SU_GRIB_API_ROOT}/include")
      if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        set(GRIB_BUILD_TYPE "Debug")
      else()
        set(GRIB_BUILD_TYPE "Release")
      endif()
      set(SU_GRIB_API_LIBRARY
          "$ENV{SU_GRIB_API_ROOT}/lib/${GRIB_BUILD_TYPE}/grib_api_lib.lib")
      message(STATUS "USE SU_GRIB_API_INCLUDE ${SU_GRIB_API_INCLUDE}.")
      message(STATUS "USE SU_GRIB_API_LIBRARY ${SU_GRIB_API_LIBRARY}.")
      include_directories(${SU_GRIB_API_INCLUDE})
      link_libraries(${SU_GRIB_API_LIBRARY})
      add_definitions("-DSU_GRIB_ENABLED=1")
    endif()
  else()
    # 指定eccodes 目录
    if("" STREQUAL "${SU_GRIB_API_ROOT}")
      if(DEFINED ENV{ECCODES_ROOT})
        set(SU_GRIB_API_ROOT "$ENV{ECCODES_ROOT}")
        set(SU_ECCCODES_SET TRUE)
      endif()
    endif()

    if(NOT SU_ECCCODES_SET)
      if(EXISTS "/usr/lib64/libeccodes.so")
        if(EXISTS "/usr/include/eccodes.h")
          set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -leccodes")
          add_definitions("-DSU_GRIB_ENABLED=1")
          include_directories("/usr/include")
          message(STATUS "Eccodes cxx header /usr/include/eccodes.h")
          message(STATUS "Eccodes dynmaic lib /usr/lib64/libeccodes.so")
        endif()
      endif()
    endif()
  endif()
endif()
