# 检查Windows平台下GRIP_API的一些信息, Linux平台下使用 ecCodes
IF(IS_WINDOWS)
    IF ("" STREQUAL "$ENV{SU_GRIB_API_ROOT}")
        message(WARNING "SU_GRIB_API_ROOT NOT FOUND.")
        add_definitions("-DSU_GRIB_ENABLED=0")
    ELSE ()
        set(SU_GRIB_API_INCLUDE "$ENV{SU_GRIB_API_ROOT}/include")
        IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
            set(GRIB_BUILD_TYPE "Debug")
        ELSE()
            set(GRIB_BUILD_TYPE "Release")
        ENDIF()
        set(SU_GRIB_API_LIBRARY "$ENV{SU_GRIB_API_ROOT}/lib/${GRIB_BUILD_TYPE}/grib_api_lib.lib")
        message(STATUS "USE SU_GRIB_API_INCLUDE ${SU_GRIB_API_INCLUDE}.")
        message(STATUS "USE SU_GRIB_API_LIBRARY ${SU_GRIB_API_LIBRARY}.")
        INCLUDE_DIRECTORIES(${SU_GRIB_API_INCLUDE})
        LINK_LIBRARIES(${SU_GRIB_API_LIBRARY})
        add_definitions("-DSU_GRIB_ENABLED=1")
    ENDIF ()
ELSE()
    # 指定eccodes 目录
    if("" STREQUAL "${SU_GRIB_API_ROOT}")
        if(DEFINED ENV{ECCODES_ROOT})
            set(SU_GRIB_API_ROOT "$ENV{ECCODES_ROOT}")
            set(SU_ECCCODES_SET TRUE)
        endif()
    endif()

    if(NOT SU_ECCCODES_SET)
        if(EXISTS "/usr/lib64/libeccodes.so")
            if(EXISTS "/usr/include/eccodes.h")
                set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -leccodes")
                add_definitions("-DSU_GRIB_ENABLED=1")
                include_directories("/usr/include")
                message(STATUS "Eccodes cxx header /usr/include/eccodes.h")
                message(STATUS "Eccodes dynmaic lib /usr/lib64/libeccodes.so")
            endif()
        endif()
    endif()

ENDIF()